services:
  # Entorno de programación
  jupyter:
    build: .
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=utn2026
    volumes:
      - .:/home/jovyan/work
    depends_on:
      - ollama

  # Motor de IA Local
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    gpus: all

volumes:
  ollama_data: